In [2]:
import numpy as np
#from numpy import linalg as LA
from scipy import linalg as LA


In [4]:
# Dynamical matrix Bi2Te3

w, v = LA.eigh(np.array ( [  [ 10.1346,  -6.89213, -0.957313, 0.307158, -0.212557], 
                             [ -6.89213, 8.90451, -3.06139, -1.07833, 0.307158 ], 
                             [-0.957313, -3.06139, 9.88004, -3.06139, -0.957313], 
                             [ 0.307158, -1.07833, -3.06139, 8.90451, -6.89213 ],
                             [ -0.212557, 0.307158, -0.957313, -6.89213, 10.1346] ] ) )

In [10]:
np.sqrt(w)

array([0.58378366, 1.72145472, 3.3341934 , 4.0212702 , 4.16732416])

In [5]:
v

array([[-3.92880291e-01,  4.93635949e-01,  3.67051027e-01,
         4.59258773e-01,  5.06284060e-01],
       [-5.12372979e-01,  5.06284060e-01,  5.71029272e-02,
        -4.83955769e-01, -4.93635949e-01],
       [-4.07722965e-01,  1.22124533e-15, -8.50896937e-01,
         3.31264827e-01,  2.22044605e-16],
       [-5.12372979e-01, -5.06284060e-01,  5.71029272e-02,
        -4.83955769e-01,  4.93635949e-01],
       [-3.92880291e-01, -4.93635949e-01,  3.67051027e-01,
         4.59258773e-01, -5.06284060e-01]])

In [9]:
a = np.array ( [  [ 10.1346,  -6.89213, -0.957313, 0.307158, -0.212557], 
    [ -6.89213, 8.90451, -3.06139, -1.07833, 0.307158 ], 
    [-0.957313, -3.06139, 9.88004, -3.06139, -0.957313], 
    [ 0.307158, -1.07833, -3.06139, 8.90451, -6.89213 ],
    [ -0.212557, 0.307158, -0.957313, -6.89213, 10.1346] ] )


k, l = LA.eig( a, left=True, right=False, homogeneous_eigvals=True)

l


array([[ 3.92880291e-01,  4.93635949e-01,  3.67051027e-01,
        -5.06284060e-01,  4.59258773e-01],
       [ 5.12372979e-01,  5.06284060e-01,  5.71029272e-02,
         4.93635949e-01, -4.83955769e-01],
       [ 4.07722965e-01, -4.10885748e-17, -8.50896937e-01,
        -2.11009454e-15,  3.31264827e-01],
       [ 5.12372979e-01, -5.06284060e-01,  5.71029272e-02,
        -4.93635949e-01, -4.83955769e-01],
       [ 3.92880291e-01, -4.93635949e-01,  3.67051027e-01,
         5.06284060e-01,  4.59258773e-01]])

In [11]:
# Dynamical matrix Bi2Se3

p, q = LA.eigh(np.array ( [  [ 18.4726, -9.8594, -1.20707, 0.434898, -0.354379], 
                             [ -9.8594, 10.2661, -4.46419, -1.31684, 0.434898 ], 
                             [-1.20707, -4.46419, 17.1233, -4.46419, -1.20707], 
                             [ 0.434898, -1.31684, -4.46419, 10.2661, -9.8594 ],
                             [ -0.354379, 0.434898, -1.20707, -9.8594, 18.4726] ] ) )


np.sqrt(p)

array([0.80826113, 2.0717263 , 4.34631055, 4.96458252, 5.11056446])

In [12]:
q

array([[-3.32539303e-01,  4.08686227e-01,  3.25824923e-01,
         5.32217748e-01,  5.77040352e-01],
       [-5.70396340e-01,  5.77040352e-01,  8.59041652e-02,
        -4.08984706e-01, -4.08686227e-01],
       [-3.57954263e-01,  7.21644966e-16, -8.79157090e-01,
         3.14565664e-01, -3.74700271e-16],
       [-5.70396340e-01, -5.77040352e-01,  8.59041652e-02,
        -4.08984706e-01,  4.08686227e-01],
       [-3.32539303e-01, -4.08686227e-01,  3.25824923e-01,
         5.32217748e-01, -5.77040352e-01]])